### ISSUE TITLE
Problem indexing empty <li>

### ISSUE THREAD

**Issue by miguelisidoro** [baynezy/Html2Markdown#325]
# Report issue

I have an error with the following stack trace:

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at Html2Markdown.Replacement.HtmlParser.ReplaceList(String html)
   at Html2Markdown.Replacement.HtmlParser.ReplaceLists(String html)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Html2Markdown.Converter.Convert(String html)

## Steps to reproduce the problem

Use the following html:

```
"<h1>Adopt OKRs as a strategy execution framework</h1>
<h2>Channel: OPSP 2023</h2>
<h2>Tags: 2023Q3ROCKS</h2>
<p><strong>Ações</strong></p>\n<ul>\n<li>✅ <a
            href=\"https://www.site.pt">Apresentação</a>
        OKRs 101 </li>\n<li>✅ Titçe\n<ul>\n<li><img
                    src=\"https://www.site.pt"></li>\n
        </ul>\n</li>\n<li>✅ Definição de \"coaches\"\n<ul>\n<li>John Doe</li>\n</ul>\n
    </li>\n<li>✅ Subtitle\n<ul>\n<li>Q4 2023</li>\n</ul>\n</li>\n<li>🕒 Tool
\n<ul>\n<li>In evaluation</li>\n</ul>\n</li>\n</ul>"
```

Thanks

**Comment by baynezy** [comment]
@miguelisidoro - I am having trouble recreating your issues.

See https://github.com/baynezy/Html2Markdown/commit/df56e844928113cce6f24dcd70422e306cd422bb#diff-cef6a552707a663cb075c5b4d94f051ed0ce36b0b1037f95b184f69c459bf965 for details. This unit test passes and does not create your link error. Can you send me a reproducible case to help me debug it?
