### ISSUE TITLE
Having an extra <ul> tag throws an error "System.InvalidOperationException: Sequence contains no elements"

### ISSUE THREAD

**Issue by shettyanusha** [baynezy/Html2Markdown#395]
# Report issue
If there is an extra `<ul>` in the html string, the package throws the below error
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at Html2Markdown.Replacement.HtmlParser.ReplaceList(String html)
   at Html2Markdown.Replacement.HtmlParser.ReplaceLists(String html)
   at Html2Markdown.Replacement.CustomReplacer.Replace(String html)
   at Html2Markdown.Converter.<>c.<Convert>b__5_0(String current, IReplacer element)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Html2Markdown.Converter.Convert(String html)

The String used to test this - 
`<ul><ul><li>first list val</li></ul></ul>`

## Expected behavior
The extra `<ul>` tag should be ignored.

## Actual Behaviour
Error 

## Steps to reproduce the problem

`var description = "<ul><ul><li>first list val</li></ul></ul>";
var converter = new Converter();
markdown = converter.Convert(description);`

**Comment by baynezy** [comment]
@shettyanusha - I am in the midst of releasing this to Nuget. It wil be in version 6.2.1.4.

Kind regards.

**Comment by ashetty-planview** [comment]
Thank you so much @baynezy
