### ISSUE TITLE
Empty lists throw an exception

### ISSUE THREAD

**Issue by deanebarker** [baynezy/Html2Markdown#88]
An empty UL or OL in the HTML will throw an uncaught exception.

Code:
```
var html = "<ul></ul>";  // Note: zero LI child elements in the UL
var converter = new Html2Markdown.Converter();
var md = converter.Convert(html);
```

Exception:
```
InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)    
at Html2Markdown.Replacement.HtmlParser.ReplaceList(String html)    
at Html2Markdown.Replacement.HtmlParser.ReplaceLists(String html)    
at Html2Markdown.Replacement.CustomReplacer.Replace(String html)    
at Html2Markdown.Converter.<>c.<Convert>b__5_0(String current, IReplacer element)    
at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)    
at Html2Markdown.Converter.Convert(String html)
```

I was processing thousands of HTML fragments, and ran into this several dozen times. It's very repeatable.

**Comment by stevetemple** [comment]
I've just happened to add a test case and fix this in my PR for non-closed li tags https://github.com/baynezy/Html2Markdown/pull/89

**Comment by stevetemple** [comment]
This should be resolved in the latest version @baynezy

**Comment by baynezy** [comment]
Thanks @stevetemple. @deanebarker can you please confirm?

**Comment by deanebarker** [comment]
Confirmed. My code snippet from above completes without error now (and returns an empty string, as expected).

**Comment by Myrga** [comment]
Hello, I have exactly the same issue as this one but with unordered list `<ol>` where if it's empty, it throws an error with `InvalidOperationException: Sequence contains no elements`.

**Comment by Chaohuiguo** [comment]
An empty UL or li in the HTML will throw an uncaught exception.

Code:
` string HtmlContent = "<ul><li></li></ul>"; // Note :UL contains LI child elements
  string mdContent = new Converter().Convert(HtmlContent);`

Exception:
`System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at Html2Markdown.Replacement.HtmlParser.ReplaceList(String html)
   at Html2Markdown.Replacement.HtmlParser.ReplaceLists(String html)
   at Html2Markdown.Replacement.CustomReplacer.Replace(String html)
   at Html2Markdown.Converter.<>c.<Convert>b__5_0(String current, IReplacer element)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Html2Markdown.Converter.Convert(String html)
   at SyncProductsandRolesListToWorkitem.unit.UnitTest1.htmltomd(String filePath) in E:\a\SourceCode\SyncProductsandRolesListToWorkitem\SyncProductsandRolesListToWorkitem.unit\UnitTest1.cs:line 29`

**Comment by baynezy** [comment]
@Chaohuiguo - can you please raise this as a new issue and I will take a look at it?
